resources:

  - name: myGitRepo
    type: gitRepo
    # replace github with your SCM integration name
    integration: github
    pointer:
      # replace devops-recipes/myapp with your source code organization and repository name.
      sourceName: niranjan-shippable/test_pipeline
      # configure branch
      branch: master
      # configure webhooks
      buildOnCommit:            true
      buildOnPullRequest:       true
      buildOnPullRequestClose:  false
      buildOnRelease:           false
      buildOnTagPush:           false


jobs:      
  ## Job description:
  - name: test-image-tagging
    type: runSh
    #runtime:
      #nodePool: custom__x86_64__WindowsServer_2016
      #container: false # run on host by default
    steps:
      - IN: myGitRepo
      - TASK:
          name: checkRunShJob
          script:
            - cd $(shipctl get_resource_state "myGitRepo")
            # run the build script
            - docker images
            - echo "sleeping 10 seconds"
            - sleep 10 
            - git clone https://github.com/niranjan92/u14phpall
            - cd u14phpall 
            - echo "starting docker build"
            - docker build -t=niranjanhub/u14phpall .
            - echo "ended docker build"
    on_success:
      script:
        - echo "Task successfully completed"
